import Head from 'next/head'
import Home from './Home'


export default function index() {
  return (
    <div>
      <Head>
        <title>Kenny portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;&600display=swap" rel="stylesheet"></link>
      </Head>
      <Home />
    </div>
  )
}
